name: bearlysocial
description: "Instantly connect with casual, intimate friends on BearlySocial."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  easy_localization: ^3.0.6
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.0
  flutter_svg: ^2.0.16
  google_ml_kit: ^0.19.0
  hashlib: ^1.21.0
  http: ^1.3.0
  http_parser: ^4.1.2
  http_status_code: ^0.0.2
  image: ^4.5.2
  internet_connection_checker_plus: ^2.7.0
  interval_time_picker: ^3.0.2+8
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  omni_datetime_picker: ^2.0.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/pngs/
    - assets/spreadsheets/
    - assets/svgs/
