import 'package:bearlysocial/constants/lang_code.dart';

class NativeLanguageName {
  static const Map<String, LanguageCode> map = {
    'English': LanguageCode.en,
    'Español': LanguageCode.es,
    'Français': LanguageCode.fr,
    'Deutsch': LanguageCode.de,
    'Italiano': LanguageCode.it,
    '日本語': LanguageCode.ja,
    '中文': LanguageCode.zh,
    'Русский': LanguageCode.ru,
    'العربية': LanguageCode.ar,
    'Português': LanguageCode.pt,
    'हिन्दी': LanguageCode.hi,
    'Bengali': LanguageCode.bn,
    '한국어': LanguageCode.ko,
    'Tiếng Việt': LanguageCode.vi,
    'Türkçe': LanguageCode.tr,
    'Polski': LanguageCode.pl,
    'Bahasa Indonesia': LanguageCode.id,
    'Nederlands': LanguageCode.nl,
    'Svenska': LanguageCode.sv,
    'Čeština': LanguageCode.cs,
    'עִבְרִית': LanguageCode.he,
    'Magyar': LanguageCode.hu,
    'Dansk': LanguageCode.da,
    'Українська': LanguageCode.uk,
    'ภาษาไทย': LanguageCode.th,
    'Ελληνικά': LanguageCode.el,
    'Română': LanguageCode.ro,
    'Norsk': LanguageCode.no,
    'Slovenský': LanguageCode.sk,
    'Suomi': LanguageCode.fi,
    'Català': LanguageCode.ca,
    'Hrvatski': LanguageCode.hr,
    'Slovenščina': LanguageCode.sl,
    'Српски': LanguageCode.sr,
    'Eesti': LanguageCode.et,
    'Lietuvių': LanguageCode.lt,
    'Latviešu': LanguageCode.lv,
    'Filipino': LanguageCode.fil,
  };
}
